- hooks/006-add-gdm.chroot
At present, GDM starts up and displays gnome-initial-setup on the initial boot when Ubuntu Core is unpacking. This is an attempt to block that until the system has fully set up and is ready to use.
> hooks: delay gdm.service until after snapd.seeded.services starts

- hooks/006-add-gdm.chroot
gsd-xsettings is still disabled, as it is still causing the session to crash.
This relies on a UCD specific rebuild of gnome-shell configured with `-Dsystemd=false`, so Xwayland starts up correctly and doesn't get stuck in `-initfd` mode.
> hooks: re-enable X11 support in gnome-shell.

- hooks/006-add-gdm.chroot
- hooks/900-cleanup-etc-var.chroot
When gnome-shell starts, it calls gnome-session's D-Bus API to set `GNOME_SETUP_DISPLAY=:1` for future processes it starts. If this environment variable is set, gsd-xsettings will try to connect to this socket in preference to `$DISPLAY`.
Unfortunately, mutter's Xwayland demand start up code only watches for connection attempts on the regular display sockets, so gsd-xsettings hangs. It never registers as a client with gnome-session, so gnome-session asks the shell to display the oops screen after the timeout expires.
> hooks: enable gsd-xsettings again

- hooks/900-cleanup-etc-var.chroot
A later command in the hooks broke when we stopped deleting /var/log/journal. So go back to deleting it, then re-create it after /var/log is cleared.
> hooks: try enabling persistent journal again

- hooks/000-provide-uids-gids.chroot
- hooks/001-zz-add-core-desktop-ppa.chroot
- hooks/006-add-gdm.chroot
- hooks/990-ensure-uids-gids.chroot
- snapcraft.yaml
This is one of the three MRs required for adding audio support to Core Desktop. This one adds the last version of PipeWire, which will be needed to add support of permissions. It also adds some extra packages needed for gnome-control-center to work as expected (for example, without libcanberra-pulse, the audio test doesn't work).
> UCD-94: Add audio support for Core Desktop

- hooks/000-provide-uids-gids.chroot
The latest snap build is failing due to reuse of uid 107 (the uid previously used by docker). Adjust the uids for rtkit and pipewire users to compensate.
> hooks: don't reuse the docker uid for rtkit

- hooks/006-add-gdm.chroot
This simple MR replaces the default pipewire session and police manager with the powerful (and useful) wireplumber, and also ensures that pipewire is installed in the core.
> Use wireplumber instead of pipewire

- hooks/001-extra-packages.chroot
This package is required to have bluetooth audio support.
> UCD-114: add libspa-bluetooth package

- hooks/006-add-gdm.chroot
This removes org.gnome.Shell.Screencast.service to prevent activation on screen recording as an unconfined service.
> Remove org.gnome.Shell.Screencast.service

- hooks/006-add-gdm.chroot
- static/usr/bin/core-desktop-session-wrapper.sh
- static/usr/share/wayland-sessions/ubuntu-desktop-session.desktop
This PR adds a version of the ubuntu-desktop-session snap's `session-wrapper.sh` script to the base snap, so it can potentially be used by other desktop session snaps.
I took the opportunity to simplify the snap a little too:
1. the script now takes the session snap command as an argument, so it should work with snaps other than ubuntu-desktop-session.
2. just symlink sockets from `$XDG_RUNTIME_DIR/snap.$snap_name` to `$XDG_RUNTIME_DIR`. We were hard linking sockets before in the hope that it would make things easier with AppArmor, but that turned out not to be the case. We also don't have to wait for the session snap to create the sockets before creating symlinks, so this gets rid of some of the background jobs.
As well as updating `ubuntu-desktop-session.desktop` to use the new wrapper …
> hooks, static: add session wrapper script, and make /etc/gdm3/custom.conf writable

- hooks/006-add-gdm.chroot
To configure the keyboard, the ibus package is required. This PR adds it. But it still requires a change in ubuntu-desktop-session for DBus activation.
It also requires https://github.com/canonical/ubuntu-desktop-session-snap/pull/19
> Add ibus package to fix keyboard setting

- hooks/006-add-gdm.chroot
Hide gnome-terminal by default, it's still available via ctrl-alt-t
> Hide gnome-terminal by default

- hooks/006-add-gdm.chroot
Dropped systemd service files for gnome-shell so we don't need a PPA build of gnome-shell
> Dropped systemd service files for gnome-shell

- hooks/006-add-gdm.chroot
Prevent launching colord-session to allow it to be dbus activated via ubuntu-desktop-session
> remove colord-session

- hooks/006-add-gdm.chroot
GDM in ubuntu applies this logic, so we should do the same for desktop on core
https://salsa.debian.org/gnome-team/gdm/-/blob/ubuntu/master/debian/patches/ubuntu/start-after-cloudinit.patch
> Delay gdm until after cloud-config is complete

- README.md
- build-package.sh
Sometimes it is desirable to test .deb packages in the core22 system before uploading them to the core-desktop PPA.
This PR allows to do this, by copying any .deb file placed in the "test-debs" folder in the project dir, and making them available to APT with the maximum priority, thus overriding any other package with the same name.
> Allow to test debian packages

- hooks/006-add-gdm.chroot
the goa page doesn't work, let's skip it for now.
> Skip the goa page in gnome-initial-setup

- hooks/006-add-gdm.chroot
Delay gdm until snapd.seeded and cloud-config are complete, rather than cloud-init which seemed to cause gdm to fail to start
> Delay gdm until snapd.seeded and cloud-config are complete

- hooks/018-set-os-release.chroot
The `release.OnCoreDesktop` check merged to upstream snapd in @robert-ancell's https://github.com/snapcore/snapd/pull/13041 depends on us setting `VARIANT_ID=desktop` in `/usr/lib/os-release` in the root file system. This change does that.
> hooks: set VARIANT_ID=desktop in /usr/lib/os-release

- hooks/002-add-locales.chroot
- hooks/006-add-gdm.chroot
When the user changes the locale, the XDG folders should be renamed to their translated names. This is done by xdg-user-dirs-gtk-update and xdg-user-dirs-update. Unfortunately, the former was missing, and also some .mo files are required for them to work.
This patch adds everything.
Unfortunately, there is still some problem: when the folders are renamed, the desktop icons disappear. After rebooting/restarting the Gnome Shell session, the icons still don't appear (it seems to be some problem with nautilus). After a new reboot/restart, the icons finally do appear.
> Update XDG folders when changing locale

- Makefile
- README.md
- generate-connections.py
- hooks/993-connect-snaps.chroot
Sometimes it is needed to be able to connect some plugs during installation. Although the right way of doing it is by editing the gadget-desktop snap, this is cumbersome for quick tests.
This patch adds a quick&dirty way of connecting the plugs during installation. It basically creates a systemd service that is run at startup and tries to connect the specified plugs. When it succeeds, it automatically disables itself.
This method must be used only during tests, never for production.
> Allow to connect specific plugs during installation

- hooks/006-add-gdm.chroot
- hooks/010-configure-system-setup-tool.chroot
- snapcraft.yaml
This PR uses ubuntu-core-desktop-init instead of gnome-session-init to configure the system.
To fully work, it requires:
- https://github.com/canonical/ubuntu-desktop-provision/pull/122
- https://github.com/canonical/ubuntu-core-desktop/pull/55
- https://github.com/canonical/ubuntu-desktop-provision/pull/144
- https://github.com/canonical/dbus.dart/pull/363
- https://github.com/canonical/ubuntu-core-desktop-init/pull/47
> Use ubuntu core desktop init for setup

- Makefile
- dconf-init-data/background-defaults
- hooks/010-configure-system-setup-tool.chroot
- snapcraft.yaml
In the first boot, the gnome shell colors are incorrect, using the default ones instead of the Yaru ones, and the background is also a blue color.
This patch fixes both bugs.
> Udeng 1681 core desktop bug oobe doesnt display proper background or theme

- hooks/000-provide-uids-gids.chroot
For the new systemd version it seems that this user is required. This patch adds it. But wait until the 249.11-0ubuntu3.12 version of systemd has been moved to backports.
> Add systemd-journal user
